apiVersion: v1
kind: Service
metadata:
  name: {{ include "coredns-etcd.fullname" . }}-coredns
  labels:
    app: coredns
    chart: {{ include "coredns-etcd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.coredns.service.type }}
  ports:
  - name: dns-udp
    port: {{ .Values.coredns.service.port }}
    targetPort: dns-udp
    protocol: UDP
  - name: dns-tcp
    port: {{ .Values.coredns.service.port }}
    targetPort: dns-tcp
    protocol: TCP
  selector:
    app: coredns
    release: {{ .Release.Name }}
